global CONTROL_PORT, CMD_VM_PHASE, CMD_VM_WALT_ADD_DEV, CMD_VM_WALT_DEV_IP, CMD_VM_WG_KEYGEN, CMD_VM_WG_DOORS, CMD_VM_WG_DEL_CONF, CMD_VM_WG_UP, CMD_VM_WG_DOWN, CMD_VM_COMMIT, CMD_VM_SHUTDOWN, CMD_VM_LIVE

CONTROL_PORT = 5555

CMD_VM_PHASE = 0

CMD_VM_WALT_ADD_DEV = 1
CMD_VM_WALT_DEV_IP = 2

CMD_VM_WG_KEYGEN = 3
CMD_VM_WG_DOORS = 4
CMD_VM_WG_DEL_CONF = 5
CMD_VM_WG_UP = 6
CMD_VM_WG_DOWN = 7

CMD_VM_COMMIT = 8
CMD_VM_SHUTDOWN = 9
CMD_VM_LIVE = 10