global CONTROL_PORT, CMD_VM_PHASE, CMD_VM_WALT_DEVS, CMD_VM_WALT_IPS, CMD_VM_WG_KEYGEN, CMD_VM_WG_DOORS, CMD_VM_WG_UP, CMD_VM_WG_DOWN, CMD_VM_COMMIT, CMD_VM_SHUTDOWN, CMD_VM_LIVE, VM_COMMANDS

CONTROL_PORT = 5555

CMD_VM_PHASE = 0

CMD_VM_WALT_DEVS = 1
CMD_VM_WALT_IPS = 2

CMD_VM_WG_KEYGEN = 3
CMD_VM_WG_DOORS = 4
CMD_VM_WG_UP = 5
CMD_VM_WG_DOWN = 6

CMD_VM_COMMIT = 7
CMD_VM_SHUTDOWN = 8
CMD_VM_LIVE = 9

VM_COMMANDS = {
"CMD_VM_PHASE":CMD_VM_PHASE,
"CMD_VM_WALT_DEVS":CMD_VM_WALT_DEVS,
"CMD_VM_WALT_IPS":CMD_VM_WALT_IPS,
"CMD_VM_WG_KEYGEN":CMD_VM_WG_KEYGEN,
"CMD_VM_WG_DOORS":CMD_VM_WG_DOORS,
"CMD_VM_WG_UP":CMD_VM_WG_UP,
"CMD_VM_WG_DOWN":CMD_VM_WG_DOWN,
"CMD_VM_COMMIT":CMD_VM_COMMIT,
"CMD_VM_SHUTDOWN":CMD_VM_SHUTDOWN,
"CMD_VM_LIVE":CMD_VM_LIVE
}