global CMD_DOOR_FIREWALL_UP, CMD_DOOR_FIREWALL_DOWN, CMD_DOOR_WG_KEYGEN, CMD_DOOR_WG_UP, CMD_DOOR_WG_DOWN, CMD_DOOR_WG_GEN_CONF, CMD_DOOR_TRAFFIC_SHAPER_UP, CMD_DOOR_TRAFFIC_SHAPER_DOWN, CMD_DOOR_LIVE

CMD_DOOR_FIREWALL_UP = 1
CMD_DOOR_FIREWALL_DOWN = 2

CMD_DOOR_WG_KEYGEN = 3
CMD_DOOR_WG_UP = 4
CMD_DOOR_WG_DOWN = 5
CMD_DOOR_WG_GEN_CONF = 6

CMD_DOOR_TRAFFIC_SHAPER_UP = 7
CMD_DOOR_TRAFFIC_SHAPER_DOWN = 8
CMD_DOOR_LIVE = 9