global CMD_DOOR_FIREWALL_UP, CMD_DOOR_FIREWALL_DOWN, CMD_DOOR_WG_KEYGEN, CMD_DOOR_WG_UP, CMD_DOOR_WG_DOWN, CMD_DOOR_WG_GEN_CONF, CMD_DOOR_TRAFFIC_SHAPER_UP, CMD_DOOR_TRAFFIC_SHAPER_DOWN, CMD_DOOR_LIVE, DOOR_COMMANDS

CMD_DOOR_FIREWALL_UP = 0
CMD_DOOR_FIREWALL_DOWN = 1

CMD_DOOR_WG_KEYGEN = 2
CMD_DOOR_WG_UP = 3
CMD_DOOR_WG_DOWN = 4
CMD_DOOR_WG_GEN_CONF = 5

CMD_DOOR_TRAFFIC_SHAPER_UP = 6
CMD_DOOR_TRAFFIC_SHAPER_DOWN = 7
CMD_DOOR_LIVE = 8

DOOR_COMMANDS = {
"CMD_DOOR_FIREWALL_UP": CMD_DOOR_FIREWALL_UP,
"CMD_DOOR_FIREWALL_DOWN": CMD_DOOR_FIREWALL_DOWN,
"CMD_DOOR_WG_KEYGEN": CMD_DOOR_WG_KEYGEN,
"CMD_DOOR_WG_UP": CMD_DOOR_WG_UP,
"CMD_DOOR_WG_DOWN": CMD_DOOR_WG_DOWN,
"CMD_DOOR_WG_GEN_CONF": CMD_DOOR_WG_GEN_CONF,
"CMD_DOOR_TRAFFIC_SHAPER_UP": CMD_DOOR_TRAFFIC_SHAPER_UP,
"CMD_DOOR_TRAFFIC_SHAPER_DOWN": CMD_DOOR_TRAFFIC_SHAPER_DOWN,
"CMD_DOOR_LIVE": CMD_DOOR_LIVE
}